model_name: 'ViT'
input_channels: 3
image_size: 128
patch_size: 16
num_classes: 1000
dim: 1024
depth: 6
heads: 16
mlp_dim: 2048
dropout: 0.1
emb_dropout: 0.3
lr: 1e-4
weight_decay: 1e-4
loss_type: 'focal'