dropblock: True
extra_fc: False
dropout: False
fifth_conv_layer: False
sn: False
half_sn: False
activation: "relu"
cifar10_normalize_inputs: False
dropblock_prob: 0.5
dropblock_size: 1
dropout_prob: 0.5
avg_pool: False
# dropblock location at the output of the nth residual layer
dropblock_location: 2
image_size: 32
epochs: 60
learning_rate: 5e-2
loss_type: "nll"
optimizer_type: "adam"
original_architecture: True