_BASE_: "../Base-Inference.yaml"

PROBABILISTIC_INFERENCE:
    # One of the following: 'standard_nms', 'mc_dropout_ensembles',
    # 'anchor_statistics', 'bayes_od', 'ensemble'
    INFERENCE_MODE: 'standard_nms'

    MC_DROPOUT:
        # Enables MC_Dropout if INFERENCE_MODE supports it.
        ENABLE: False
        NUM_RUNS: 1
        AFTER_INFERENCE: True
