_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  WEIGHTS: "./data/VOC-Detection/faster-rcnn/faster_rcnn_R_50_FPN_all_logistic/random_seed_0/model_final.pth"
  WEIGHTS: "../model_final_vanilla_resnet_bdd.pth"
  #WEIGHTS: "data/BDD-Detection/faster-rcnn/vanilla/random_seed_0/model_best_lr2e-4.pth"

#  PROPOSAL_GENERATOR:
#    NAME: "RPNLogistic"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "StandardROIHeads"
    NUM_CLASSES: 10
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('bdd_custom_train',)
  TEST: ('bdd_custom_val',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (60000, 80000)
#  MAX_ITER: 90000  # 17.4 epochs: 4365 steps per epoch with batch-size of 16
  MAX_ITER: 52000  # 10 epochs at batch_size 16
#  MAX_ITER: 208000  # 10 epochs at batch_size 4
  WARMUP_ITERS: 1000
  SAVE_LAST_CHECKPOINTS: 2
  SAVE_BEST_CHECKPOINTS: 2
  VAL_METRIC: "bbox/AP50"
  VAL_METRIC_MODE: "max"
  FREEZE_BACKBONE: True
  FREEZE_RPN: False
  FREEZE_BOX_POOLER: False
DATALOADER:
    NUM_WORKERS: 8  # Depends on the available memory
TEST:
  EVAL_PERIOD: 1000  # Has to be the same as Checkpoint period